# -*- coding: utf-8 -*-
"""136. Single Number

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lU0zqiuGxTA_uYdPSPhgFs1hGZqvmjvG

Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.

You must implement a solution with a linear runtime complexity and use only constant extra space.
"""

class Solution:
    def singleNumber(self, nums: List[int]) -> int:

        unique = set(nums)
        sort_list = list(unique)
        for i in range(len(sort_list)):
            if sort_list[i] in nums and nums.count(sort_list[i])<2:
                return (sort_list[i])

            else:
                continue

