# -*- coding: utf-8 -*-
"""206.Reverse_Linked_List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16HwmGPCkFolSqY1QZ9HuAFBgsmRs2G8n

Given the head of a singly linked list, reverse the list, and return the reversed list.
"""

# Definition for singly-linked list.
# class ListNode(object):
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution(object):
    def reverseList(self, head):
        """
        :type head: ListNode
        :rtype: ListNode
        """
        new_list = None
        current = head
        while current:
            next_node = current.next
            current.next= new_list
            new_list = current
            current = next_node
        return new_list