# -*- coding: utf-8 -*-
"""2427_Number_of_Common_Factors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gd_RXF1gscwan8MPcbm6X2YNJZ1zxK77

Given two positive integers a and b, return the number of common factors of a and b.

An integer x is a common factor of a and b if x divides both a and b.
"""

class Solution:
    def commonFactors(self, a: int, b: int) -> int:
        x = []
        if a>b:
            length = b
        else:
            length = a

        for i in range(1,length+1):
            if a%i==0 and b%i==0:
                x.append(i)
        return(len(x))