# -*- coding: utf-8 -*-
"""345_Reverse_Vowels_of_a_String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gd_RXF1gscwan8MPcbm6X2YNJZ1zxK77

Given a string s, reverse only all the vowels in the string and return it.

The vowels are 'a', 'e', 'i', 'o', and 'u', and they can appear in both lower and upper cases, more than once.
"""

class Solution:
    def reverseVowels(self, s: str) -> str:
        vowel={'a','e','i','o','u','A','E','I','O','U'}
        vowel_list = []
        i = 0
        j = 0
        t = ''
        while i<len(s):
            if s[i] in vowel:
                vowel_list.append(s[i])
            i +=1

        while j<len(s):
            if s[j] in vowel:
                t=t+vowel_list[-1]
                del (vowel_list[-1])

            else:
                t = t+s[j]
            j += 1
        return t