# -*- coding: utf-8 -*-
"""347_Top_K_Frequent_Elements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gd_RXF1gscwan8MPcbm6X2YNJZ1zxK77

Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.
"""

class Solution:
    def topKFrequent(self, nums: List[int], k: int) -> List[int]:
        frequency = {}
        for key in nums:
            if key not in frequency:
                frequency[key] = 1
            else:
                frequency[key] += 1
        frequency_sorted = sorted(frequency.items(), key = lambda x:x[1], reverse= True)

        converted_dict = dict(frequency_sorted[:k])

        return (list(converted_dict.keys()))