# -*- coding: utf-8 -*-
"""36_Valid_sudoku.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gd_RXF1gscwan8MPcbm6X2YNJZ1zxK77

Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the following rules:

Each row must contain the digits 1-9 without repetition.
Each column must contain the digits 1-9 without repetition.
Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.
"""

class Solution:
    def isValidSudoku(self, board: List[List[str]]) -> bool:
        for m in range(0,7,3):
            for n in range(0,7,3):
                unique = set()
                for k in range(3):
                    k=k+m
                    for l in range(3):
                        l=l+n
                        digit=board[k][l]
                        if digit == '.':
                            continue
                        else:
                            if int(digit) <= 9:
                                if digit in unique:
                                    return False
                                else:
                                    unique.add(digit)
        for i in range(9):
            unique = set()
            for j in range(9):
                digit=board[j][i]
                if digit == '.':
                    continue
                else:
                    if int(digit) <= 9:
                        if digit in unique:
                            return False
                        else:
                            unique.add(digit)
        for i in range(9):
            unique = set()
            for j in range(9):
                digit=board[i][j]
                if digit == '.':
                    continue
                else:
                    if int(digit) <= 9:
                        if digit in unique:
                            return False
                        else:
                            unique.add(digit)

        return True

for l in range(0,7,3):
  print(l)