# -*- coding: utf-8 -*-
"""69_Sqrt(x).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gd_RXF1gscwan8MPcbm6X2YNJZ1zxK77

Given a non-negative integer x, return the square root of x rounded down to the nearest integer. The returned integer should be non-negative as well.

You must not use any built-in exponent function or operator.

For example, do not use pow(x, 0.5) in c++ or x ** 0.5 in python.
"""

class Solution:
    def mySqrt(self, x: int) -> int:
        if x > 1:
            for i in range(1,(x+1)):
                if (i*i) > x:
                    return(i-1)
                    break